version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: securisk-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: securisk_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - securisk-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/securisk_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: securisk-backend
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=securisk_db
      - SECRET_KEY=change-this-secret-key-in-production-min-32-chars-long
      - ALGORITHM=HS256
      - ENVIRONMENT=production
      - DEBUG=false
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - securisk-network
    healthcheck:
      test: curl -f http://localhost:8001/docs || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost/api
    container_name: securisk-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - securisk-network

  nginx:
    image: nginx:alpine
    container_name: securisk-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
      - frontend
    networks:
      - securisk-network

volumes:
  mongodb_data:
    driver: local

networks:
  securisk-network:
    driver: bridge
